name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: krdlab/setup-haxe@v1.4.0
        with:
          haxe-version: 4.2.5
      - name: Setup
        run: |
          haxelib dev wtri .
          haxelib install haxelib.json
          haxelib install hashlink
          haxelib install hxcpp
          haxelib git om.core https://github.com/omlib/om.core
          haxelib git om.http https://github.com/omlib/om.http
      - name: Build hl
        run: haxe include.hxml -hl wtri.hl
      - name: Build hlc
        run: haxe include.hxml -hl out/main.c
      - name: Build neko
        run: haxe include.hxml -neko wtri.n
      - name: Build python
        run: haxe include.hxml -python wtri.py
      - name: Build jvm
        run: haxe include.hxml -lua wtri.lua -D lua-vanilla -D lua-jit
      - name: Build cpp
        run: haxe include.hxml -cpp cpp
      - name: Build php
        run: haxe include.hxml -php php
