name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: krdlab/setup-haxe@v1.1.7
        with:
          haxe-version: 4.2.5
      - name: Setup
        run: |
          haxelib dev wtri .
          haxelib install haxelib.json
          haxelib git om.core https://github.com/omlib/om.core
          haxelib git om.http https://github.com/omlib/om.http
      - name: Build
        run: |
          haxe build.hxml -hl wtri.hl
