name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        haxe:
        - latest
        - 4.3.3
    steps:
      - uses: actions/checkout@v3
      - name: Install haxe
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: ${{ matrix.haxe }}
      - name: Install haxelibs
        run: |
          haxelib dev wtri .
          haxelib install haxelib.json
          haxelib install hashlink
          haxelib install hxcpp
          haxelib git hxargs https://github.com/Simn/hxargs
          haxelib git om.core https://github.com/omlib/om.core
          haxelib git om.http https://github.com/omlib/om.http
      - name: Build hl
        run: haxe wtri.hxml -hl wtri.hl
      - name: Build hlc
        run: haxe wtri.hxml -hl out/main.c
      - name: Build neko
        run: haxe wtri.hxml -neko wtri.n
      - name: Build python
        run: haxe wtri.hxml -python wtri.py
      - name: Build jvm
        run: haxe wtri.hxml -lua wtri.lua -D lua-vanilla -D lua-jit
      - name: Build cpp
        run: haxe wtri.hxml -cpp cpp
      - name: Build php
        run: haxe wtri.hxml -php php
